const type = {}
	type.GET_USER_INFO = 'GET_USER_INFO'

	type.FRIEND_LIST = 'FRIEND_LIST'
	type.GET_FRIEND_INFO = 'GET_FRIEND_INFO'
	type.ADD_FRIEND = 'ADD_FRIEND'
	type.DELETE_FRIEND = 'DELETE_FRIEND'
    type.UPDATE_FRIEND_INFO = 'UPDATE_FRIEND_NFO'


	type.GROUP_LIST = 'GROUP_LIST'
	type.GET_GROUP_INFO = 'GET_GROUP_INFO'
	type.ADD_GROUP = 'ADD_GROUP'
	type.DELETE_GROUP = 'DELETE_GROUP'
	type.UPDATE_GROUP_INFO = 'UPDATE_GROUP_NAME'
	type.GET_GROUP_NOTICE = 'GET_GROUP_NOTICE'

	type.LOCAL_SEARCH_RESULT = 'LOCAL_SEARCH_RESULT'
	type.CLEAR_LOCAL_SEARCH_RESULT = 'CLEAR_LOCAL_SEARCH_RESULT'
	type.SEARCH_CONTENT = 'SEARCH_CONTENT'

	type.CONVERSATION_LIST = 'CONVERSATION_LIST'
	type.UPDATE_CONVERSATION_SENTTIME = 'UPDATE_CONVERSATION_SENTTIME'
	type.UPDATE_CONVERSATION_LATESTMSG = 'UPDATE_CONVERSATION_MESSAGE_LATESTMSG'
	type.UPDATE_CONVERSATION_SENDERNAME = 'UPDATE_CONVERSATION_MESSAGE_SENDERNAME'
	type.UPDATE_CONVERSATION_UNREADCOUNT = 'UPDATE_CONVERSATION_UNREADCOUNT'
	type.UPDATE_CONVERSATION_NICKNAME = 'UPDATE_CONVERSATION_NICKNAME'
	type.UPDATE_CONVERSATION_ICON = 'UPDATE_CONVERSATION_ICON'
	type.ADD_ONE_CONVERSATION = 'ADD_ONE_CONVERSATION'
	type.DELETE_ONE_CONVERSATION = 'DELETE_ONE_CONVERSATION'
	type.TOGGLE_CURRENT_CONVERSATION = 'TOGGLE_CURRENT_CONVERSATION'

	type.GET_TOTAL_UNREAD_COUNT = 'GET_TOTAL_UNREAD_COUNT'

  type.CLEAR_CON_MESSAGE_LIST = 'CLEAR_CON_MESSAGE_LIST'
	type.ADD_ONE_MESSAGE = 'ADD_ONE_MESSAGE'
	type.SHIFT_ONE_MESSAGE = 'SHIFT_ONE_MESSAGE'
export default type
